-- ============================================================
-- AI Skill 评测聚合平台 — 第三批新 AI 工具 (seed-batch3.sql)
-- 版本: v1.0 (2026-08-13)
-- 用法: 在 init.sql + seed-extended.sql 之后执行
-- 数据来源: 2026 AI工具市场调研（56个新工具）
-- 目标: 数据库总 Skill 数突破 200+
-- 幂等设计: ON CONFLICT (slug) DO NOTHING
-- ============================================================

-- ============================================================
-- 1. 新增 56 个 AI 工具 Skill
-- ============================================================

INSERT INTO skills (name, slug, tagline, category, platform_id, install_url, icon_url,
                    developer_name, version, status, trial_enabled, trial_config, source, last_updated) VALUES
('Runway Gen-4', 'runway-gen4', 'AI视频生成，Gen-4模型文本/图片生成电影级视频，创意控制强', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://runwayml.com', NULL, 'Runway', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Pika Labs', 'pika-labs', 'AI短视频生成，风格化动画和特效视频，社交媒体内容', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://pika.art', NULL, 'Pika Labs', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('HeyGen', 'heygen', 'AI数字人视频，200+逼真虚拟人形象+唇形同步+多语言本地化', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://www.heygen.com', NULL, 'HeyGen', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Synthesia', 'synthesia', '企业级AI视频制作，文本/文档/PPT转交互式培训视频', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://www.synthesia.io', NULL, 'Synthesia', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Kling AI', 'kling-ai', '快手可灵AI视频生成，高质量文本/图片生成视频', 'scene', (SELECT id FROM platforms WHERE slug='qwen'),
  'https://klingai.com', NULL, 'Kuaishou', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Hailuo AI', 'hailuo-video', 'MiniMax海螺AI视频生成，电影质感文生视频', 'scene', (SELECT id FROM platforms WHERE slug='qwen'),
  'https://hailuoai.video', NULL, 'MiniMax', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Sora', 'sora', 'OpenAI文生视频模型，高质量长视频生成，集成ChatGPT使用', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://openai.com/sora', NULL, 'OpenAI', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Google Veo 3', 'veo-3', 'Google DeepMind视频生成，高质量文生/图生视频+同步音频', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://deepmind.google/veo', NULL, 'Google', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Higgsfield', 'higgsfield', 'AI动态图像和视频生成，创意风格化内容制作', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://higgsfield.ai', NULL, 'Higgsfield', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Descript', 'descript', 'AI视频/播客编辑，像编辑文档一样编辑视频+自动转录', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://www.descript.com', NULL, 'Descript', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Opus Clip', 'opus-clip', 'AI长视频转短视频，自动剪辑精华片段+AI字幕+病毒分数', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://www.opus.pro', NULL, 'Opus', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Midjourney v6', 'midjourney-v6', '顶级AI图像生成，品牌/广告/艺术创意图像质量行业标杆', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://www.midjourney.com', NULL, 'Midjourney', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Adobe Firefly', 'adobe-firefly', 'Adobe生成式AI，图像/视频/音频生成，嵌入PS/AI/PR工作流', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://firefly.adobe.com', NULL, 'Adobe', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('FLUX', 'flux-image', '开源AI图像模型，高质量文生图+API集成+本地部署', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://blackforestlabs.ai', NULL, 'Black Forest Labs', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Ideogram', 'ideogram', 'AI图像生成，文字渲染能力最强，Logo/海报设计首选', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://ideogram.ai', NULL, 'Ideogram', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Recraft', 'recraft', 'AI图形设计，矢量图输出+品牌设计完整工作流', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://www.recraft.ai', NULL, 'Recraft', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Leonardo AI', 'leonardo-ai', 'AI图像生成，免费额度充足+API+游戏资产生成', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://leonardo.ai', NULL, 'Leonardo', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Krea AI', 'krea-ai', '实时AI图像生成和增强，创意迭代+图像放大修复', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://www.krea.ai', NULL, 'Krea', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Stable Diffusion', 'stable-diffusion', '开源AI图像生成，ComfyUI/WebUI本地部署，完全可控', 'scene', (SELECT id FROM platforms WHERE slug='dify'),
  'https://stability.ai', NULL, 'Stability AI', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Suno', 'suno-music', 'AI音乐生成，文本生成完整歌曲含人声+多种曲风', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://suno.com', NULL, 'Suno', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('ElevenLabs', 'elevenlabs-tts', '顶级AI语音合成，逼真TTS+语音克隆+多语言配音', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://elevenlabs.io', NULL, 'ElevenLabs', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Udio', 'udio-music', 'AI音乐生成，高质量文生音乐+歌词+多种流派', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://www.udio.com', NULL, 'Udio', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Google Lyria', 'lyria-music', 'Google AI音乐生成模型，高质量音乐创作', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://aitestkitchen.withgoogle.com', NULL, 'Google', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Murf AI', 'murf-tts', 'AI配音工具，120+语言自然语音合成+视频配音工作流', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://murf.ai', NULL, 'Murf', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('PlayHT', 'playht-tts', 'AI语音合成平台，实时TTS+语音克隆+API集成', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://play.ht', NULL, 'PlayHT', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Cursor', 'cursor-ide', 'AI原生代码编辑器，全仓库理解+多文件编辑+Tab补全', 'scene', (SELECT id FROM platforms WHERE slug='codex'),
  'https://cursor.com', NULL, 'Anysphere', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Windsurf', 'windsurf-ide', 'AI优先代码编辑器，Cascade智能代理+自动补全', 'scene', (SELECT id FROM platforms WHERE slug='codex'),
  'https://codeium.com/windsurf', NULL, 'Codeium', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Replit Agent', 'replit-agent', '浏览器AI编程平台，内置托管+数据库+一键部署', 'scene', (SELECT id FROM platforms WHERE slug='codex'),
  'https://replit.com', NULL, 'Replit', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('v0 by Vercel', 'v0-vercel', 'Vercel AI前端生成，自然语言转React/Next.js组件', 'scene', (SELECT id FROM platforms WHERE slug='codex'),
  'https://v0.dev', NULL, 'Vercel', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Bolt.new', 'bolt-new', '浏览器AI全栈开发，提示词转完整Web应用+即时预览', 'scene', (SELECT id FROM platforms WHERE slug='codex'),
  'https://bolt.new', NULL, 'StackBlitz', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Lovable', 'lovable-dev', 'AI全栈应用构建器，非技术人员也能开发完整应用', 'scene', (SELECT id FROM platforms WHERE slug='codex'),
  'https://lovable.dev', NULL, 'Lovable', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Devin', 'devin-ai', 'Cognition自主AI软件工程师，端到端任务执行+PR提交', 'scene', (SELECT id FROM platforms WHERE slug='codex'),
  'https://devin.ai', NULL, 'Cognition', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('GitHub Copilot', 'github-copilot', 'GitHub AI编程助手，IDE内代码补全+Chat+PR审查', 'scene', (SELECT id FROM platforms WHERE slug='codex'),
  'https://github.com/features/copilot', NULL, 'GitHub', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Google Antigravity', 'google-antigravity', 'Google AI编程平台，并行代理执行+76%SWE-bench通过率', 'scene', (SELECT id FROM platforms WHERE slug='codex'),
  'https://antigravity.google', NULL, 'Google', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Base44', 'base44', 'AI应用构建器，快速原型到生产部署+集成能力', 'scene', (SELECT id FROM platforms WHERE slug='codex'),
  'https://base44.com', NULL, 'Base44', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Create.xyz', 'create-xyz', 'AI全栈应用生成器，可视化+自然语言构建完整Web应用', 'scene', (SELECT id FROM platforms WHERE slug='codex'),
  'https://www.create.xyz', NULL, 'Create', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Perplexity', 'perplexity-ai', 'AI搜索引擎，实时联网+引用来源的深度问答+Pro搜索', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://www.perplexity.ai', NULL, 'Perplexity', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('NotebookLM', 'notebooklm', 'Google文档AI助手，多源摘要+播客生成+精确引用', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://notebooklm.google.com', NULL, 'Google', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Elicit', 'elicit-research', 'AI学术文献综述，结构化数据提取+系统评价自动化', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://elicit.com', NULL, 'Elicit', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('SciSpace', 'scispace', 'AI论文阅读助手，PDF对话+文献管理+引用追踪', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://typeset.io', NULL, 'SciSpace', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Connected Papers', 'connected-papers', 'AI引文图谱可视化，发现相关研究和学术脉络', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://www.connectedpapers.com', NULL, 'Connected Papers', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Research Rabbit', 'research-rabbit', 'AI论文推荐和引用追踪，学术发现+协作工具', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://www.researchrabbit.ai', NULL, 'Research Rabbit', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Scite', 'scite-ai', 'AI引用分析，验证引用的支持/反对/提及上下文', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://scite.ai', NULL, 'Scite', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Semantic Scholar', 'semantic-scholar', 'AI学术论文搜索引擎，2亿+论文免费检索+影响力分析', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://www.semanticscholar.org', NULL, 'Allen Institute', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Komo AI', 'komo-search', 'AI搜索引擎，快速精准的带引用问答+无广告+隐私优先', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://komo.ai', NULL, 'Komo', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Gamma', 'gamma-app', 'AI演示文稿/文档/网页生成，笔记秒变精美PPT', 'efficiency', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://gamma.app', NULL, 'Gamma', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Napkin AI', 'napkin-ai', '文本转图表/可视化，自动生成信息图和流程图', 'efficiency', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://www.napkin.ai', NULL, 'Napkin', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Otter.ai', 'otter-ai', 'AI会议记录，实时转录+摘要+行动项+多平台集成', 'efficiency', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://otter.ai', NULL, 'Otter', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Fathom', 'fathom-meeting', 'AI会议助手，Zoom录制+AI摘要+行动项提取+搜索', 'efficiency', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://fathom.video', NULL, 'Fathom', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Notion AI', 'notion-ai', 'Notion内置AI，写作/摘要/翻译/问答/数据库填充', 'efficiency', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://www.notion.so/product/ai', NULL, 'Notion', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('SlidesGPT', 'slidesgpt', 'AI PPT生成，主题描述自动生成精美演示文稿模板', 'efficiency', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://www.slidesgpt.com', NULL, 'SlidesGPT', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Tome', 'tome-app', 'AI演示文稿生成，提示词转交互式叙事PPT+多模态', 'efficiency', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://tome.app', NULL, 'Tome', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Fireflies AI', 'fireflies-ai', 'AI会议助手，跨平台会议录制+转录+智能摘要+协作搜索', 'efficiency', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://fireflies.ai', NULL, 'Fireflies', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Granola', 'granola-notes', 'AI会议笔记，macOS原生应用+自动润色会议记录+离线', 'efficiency', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://granola.ai', NULL, 'Granola', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Gumloop', 'gumloop', 'AI工作流自动化画布，可视化数据/AI管道+内置LLM', 'efficiency', (SELECT id FROM platforms WHERE slug='n8n'),
  'https://www.gumloop.com', NULL, 'Gumloop', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Lindy AI', 'lindy-ai', 'AI原生代理自动化，邮件/日历智能助手+多步骤工作流', 'efficiency', (SELECT id FROM platforms WHERE slug='n8n'),
  'https://www.lindy.ai', NULL, 'Lindy', NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Make', 'make-automation', '可视化工作流自动化，8000+应用集成+高级逻辑', 'efficiency', (SELECT id FROM platforms WHERE slug='n8n'),
  'https://www.make.com', NULL, 'Make', NULL, 'published', FALSE, NULL, 'listed', NOW())

ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- 2. Skill × 场景关联
-- ============================================================

INSERT INTO skill_scenarios (skill_id, scenario_id) VALUES
  ((SELECT id FROM skills WHERE slug='runway-gen4'), (SELECT id FROM scenarios WHERE slug='video')),
  ((SELECT id FROM skills WHERE slug='runway-gen4'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='pika-labs'), (SELECT id FROM scenarios WHERE slug='video')),
  ((SELECT id FROM skills WHERE slug='heygen'), (SELECT id FROM scenarios WHERE slug='video')),
  ((SELECT id FROM skills WHERE slug='heygen'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='synthesia'), (SELECT id FROM scenarios WHERE slug='video')),
  ((SELECT id FROM skills WHERE slug='synthesia'), (SELECT id FROM scenarios WHERE slug='office')),
  ((SELECT id FROM skills WHERE slug='kling-ai'), (SELECT id FROM scenarios WHERE slug='video')),
  ((SELECT id FROM skills WHERE slug='hailuo-video'), (SELECT id FROM scenarios WHERE slug='video')),
  ((SELECT id FROM skills WHERE slug='sora'), (SELECT id FROM scenarios WHERE slug='video')),
  ((SELECT id FROM skills WHERE slug='sora'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='veo-3'), (SELECT id FROM scenarios WHERE slug='video')),
  ((SELECT id FROM skills WHERE slug='higgsfield'), (SELECT id FROM scenarios WHERE slug='video')),
  ((SELECT id FROM skills WHERE slug='descript'), (SELECT id FROM scenarios WHERE slug='video')),
  ((SELECT id FROM skills WHERE slug='descript'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='opus-clip'), (SELECT id FROM scenarios WHERE slug='video')),
  ((SELECT id FROM skills WHERE slug='opus-clip'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='midjourney-v6'), (SELECT id FROM scenarios WHERE slug='design')),
  ((SELECT id FROM skills WHERE slug='midjourney-v6'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='adobe-firefly'), (SELECT id FROM scenarios WHERE slug='design')),
  ((SELECT id FROM skills WHERE slug='adobe-firefly'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='flux-image'), (SELECT id FROM scenarios WHERE slug='design')),
  ((SELECT id FROM skills WHERE slug='ideogram'), (SELECT id FROM scenarios WHERE slug='design')),
  ((SELECT id FROM skills WHERE slug='recraft'), (SELECT id FROM scenarios WHERE slug='design')),
  ((SELECT id FROM skills WHERE slug='leonardo-ai'), (SELECT id FROM scenarios WHERE slug='design')),
  ((SELECT id FROM skills WHERE slug='krea-ai'), (SELECT id FROM scenarios WHERE slug='design')),
  ((SELECT id FROM skills WHERE slug='krea-ai'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='stable-diffusion'), (SELECT id FROM scenarios WHERE slug='design')),
  ((SELECT id FROM skills WHERE slug='stable-diffusion'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='suno-music'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='suno-music'), (SELECT id FROM scenarios WHERE slug='video')),
  ((SELECT id FROM skills WHERE slug='elevenlabs-tts'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='elevenlabs-tts'), (SELECT id FROM scenarios WHERE slug='video')),
  ((SELECT id FROM skills WHERE slug='udio-music'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='lyria-music'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='murf-tts'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='playht-tts'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='cursor-ide'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='cursor-ide'), (SELECT id FROM scenarios WHERE slug='ui-design')),
  ((SELECT id FROM skills WHERE slug='windsurf-ide'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='windsurf-ide'), (SELECT id FROM scenarios WHERE slug='ui-design')),
  ((SELECT id FROM skills WHERE slug='replit-agent'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='v0-vercel'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='v0-vercel'), (SELECT id FROM scenarios WHERE slug='ui-design')),
  ((SELECT id FROM skills WHERE slug='bolt-new'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='bolt-new'), (SELECT id FROM scenarios WHERE slug='ui-design')),
  ((SELECT id FROM skills WHERE slug='lovable-dev'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='lovable-dev'), (SELECT id FROM scenarios WHERE slug='ui-design')),
  ((SELECT id FROM skills WHERE slug='devin-ai'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='github-copilot'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='github-copilot'), (SELECT id FROM scenarios WHERE slug='data-analysis')),
  ((SELECT id FROM skills WHERE slug='google-antigravity'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='base44'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='create-xyz'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='perplexity-ai'), (SELECT id FROM scenarios WHERE slug='research')),
  ((SELECT id FROM skills WHERE slug='perplexity-ai'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='notebooklm'), (SELECT id FROM scenarios WHERE slug='research')),
  ((SELECT id FROM skills WHERE slug='notebooklm'), (SELECT id FROM scenarios WHERE slug='office')),
  ((SELECT id FROM skills WHERE slug='elicit-research'), (SELECT id FROM scenarios WHERE slug='research')),
  ((SELECT id FROM skills WHERE slug='scispace'), (SELECT id FROM scenarios WHERE slug='research')),
  ((SELECT id FROM skills WHERE slug='connected-papers'), (SELECT id FROM scenarios WHERE slug='research')),
  ((SELECT id FROM skills WHERE slug='research-rabbit'), (SELECT id FROM scenarios WHERE slug='research')),
  ((SELECT id FROM skills WHERE slug='scite-ai'), (SELECT id FROM scenarios WHERE slug='research')),
  ((SELECT id FROM skills WHERE slug='semantic-scholar'), (SELECT id FROM scenarios WHERE slug='research')),
  ((SELECT id FROM skills WHERE slug='komo-search'), (SELECT id FROM scenarios WHERE slug='research')),
  ((SELECT id FROM skills WHERE slug='gamma-app'), (SELECT id FROM scenarios WHERE slug='office')),
  ((SELECT id FROM skills WHERE slug='gamma-app'), (SELECT id FROM scenarios WHERE slug='design')),
  ((SELECT id FROM skills WHERE slug='napkin-ai'), (SELECT id FROM scenarios WHERE slug='office')),
  ((SELECT id FROM skills WHERE slug='napkin-ai'), (SELECT id FROM scenarios WHERE slug='design')),
  ((SELECT id FROM skills WHERE slug='otter-ai'), (SELECT id FROM scenarios WHERE slug='office')),
  ((SELECT id FROM skills WHERE slug='fathom-meeting'), (SELECT id FROM scenarios WHERE slug='office')),
  ((SELECT id FROM skills WHERE slug='notion-ai'), (SELECT id FROM scenarios WHERE slug='office')),
  ((SELECT id FROM skills WHERE slug='notion-ai'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='slidesgpt'), (SELECT id FROM scenarios WHERE slug='office')),
  ((SELECT id FROM skills WHERE slug='slidesgpt'), (SELECT id FROM scenarios WHERE slug='design')),
  ((SELECT id FROM skills WHERE slug='tome-app'), (SELECT id FROM scenarios WHERE slug='office')),
  ((SELECT id FROM skills WHERE slug='tome-app'), (SELECT id FROM scenarios WHERE slug='design')),
  ((SELECT id FROM skills WHERE slug='fireflies-ai'), (SELECT id FROM scenarios WHERE slug='office')),
  ((SELECT id FROM skills WHERE slug='granola-notes'), (SELECT id FROM scenarios WHERE slug='office')),
  ((SELECT id FROM skills WHERE slug='gumloop'), (SELECT id FROM scenarios WHERE slug='automation')),
  ((SELECT id FROM skills WHERE slug='lindy-ai'), (SELECT id FROM scenarios WHERE slug='automation')),
  ((SELECT id FROM skills WHERE slug='make-automation'), (SELECT id FROM scenarios WHERE slug='automation'))

ON CONFLICT DO NOTHING;
