-- ============================================================
-- AI Skill 评测聚合平台 — 扩展种子数据 (seed-extended.sql)
-- 版本: v1.0 (2026-08-13)
-- 用法: 在 init.sql 之后执行，扩充数据库到 150+ 个 Skill
-- 数据来源: 6 份深度评测文件 + 88 个基础收录 JSON
-- 幂等设计: ON CONFLICT (slug) DO NOTHING
-- ============================================================

-- ============================================================
-- 1. 新增平台（openclaw / mcp / n8n / poe / flowise / agensi / claude-code）
-- ============================================================
INSERT INTO platforms (name, slug, description, base_url, api_supported, sort_order) VALUES
  ('OpenClaw', 'openclaw', '社区 Skill 市场（13,700+ 技能）', 'https://clawhub.com', TRUE, 11),
  ('MCP', 'mcp', 'Model Context Protocol 生态服务器', 'https://modelcontextprotocol.io', TRUE, 12),
  ('n8n', 'n8n', '开源工作流自动化平台', 'https://n8n.io', TRUE, 13),
  ('Poe', 'poe', 'Quora AI 聊天平台', 'https://poe.com', TRUE, 14),
  ('Flowise', 'flowise', '开源 LLM 应用构建器', 'https://flowiseai.com', TRUE, 15),
  ('Agensi', 'agensi', 'AI Agent 构建平台', 'https://agensi.ai', TRUE, 16),
  ('Claude Code', 'claude-code', 'Anthropic 编程 Agent', 'https://claude.ai/product', FALSE, 17)
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- 2. 深度评测 Skill（32 个）— skills + evaluations
-- ============================================================

INSERT INTO skills (name, slug, tagline, description, category, platform_id, install_url, icon_url,
                    developer_name, version, status, trial_enabled, trial_config, source, last_updated) VALUES
('Hermes 能力增强中枢', 'hermes-self-improvement', '能力增强中枢：KB/成本/决策/错误/纠正/验证/网关/记忆，startup自动加载', 'Hermes Agent 的能力增强工具集：知识库搜索、成本审计、决策记录、错误归档、纠正追踪、验证体系、LLM API网关、记忆层。startup 时自动加载，是整个 Hermes 防幻觉和质量管控体系的入口。包含 hindsight-api、hermes-knowledge-base 等 8 个子模块。', 'infrastructure', (SELECT id FROM platforms WHERE slug='hermes'),
  'https://hermes-agent.nousresearch.com', NULL, 'Nous Research', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('Hermes Hook 引擎', 'hermes-hooks', '21种Hook+40条规则Plugin+经验tag路由+防幻觉', 'Hermes 的 Hook 驱动引擎：21 种 Hook（pre/post_tool_call, pre/post_llm_call 等）+ 40 条规则 Plugin + 经验 tag 路由 + 防幻觉四层防御。进程级拦截层是 Hermes 相对 OpenClaw 最大的架构差异化优势——在 LLM 调用前拦截，省 token 又防错。', 'infrastructure', (SELECT id FROM platforms WHERE slug='hermes'),
  'https://hermes-agent.nousresearch.com', NULL, 'Nous Research', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('Hook 优先方法论', 'hook-first-methodology', '方案选择铁律：强制用最强机制 Plugin/Hook>Cron>Memory>Skill', '方案选择方法论型 Skill：做方案选择时强制用最强机制。机制强度排序 Plugin/Hook > Cron > Memory > Skill。防止"写在 memory 里被忽略"的偷懒行为。', 'infrastructure', (SELECT id FROM platforms WHERE slug='hermes'),
  'https://hermes-agent.nousresearch.com', NULL, 'Nous Research', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('Hermes 向量知识库', 'hermes-knowledge-base', 'DuckDB+text2vec 768维向量搜索，中文语义检索项目文档', 'DuckDB + text2vec 768 维向量搜索引擎：72 篇文档本地语义检索。中文语义检索项目文档、历史决策、技术方案。kb_vec.py 注入检索结果约 500-2000 token。', 'infrastructure', (SELECT id FROM platforms WHERE slug='hermes'),
  'https://hermes-agent.nousresearch.com', NULL, 'Nous Research', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('Claude Code 委派引擎', 'claude-code', '代码委派引擎：Print模式非交互+PTY模式多轮迭代', '将编码任务委派给 Claude Code CLI。Print 模式（-p）非交互一次性任务，PTY 模式多轮迭代。自动读/写文件、执行 shell、管理 git。Hermes 多 Agent 编排（GLM 规划→Claude Code 执行→GLM 验收）是开发者场景的核心竞争力。', 'infrastructure', (SELECT id FROM platforms WHERE slug='hermes'),
  'https://claude.ai/product', NULL, 'Nous Research', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('GitHub PR 全生命周期', 'github-pr-workflow', 'PR全生命周期：分支→提交→开PR→CI监控→自动修复→合并', 'PR 全生命周期管理：分支创建→提交→开 PR→CI 监控→自动修复→合并。双路径设计（gh CLI + curl 降级），任何环境都能用。GitHub API 稳定，CI 轮询逻辑健壮（30s 间隔，最多 20 次）。', 'efficiency', (SELECT id FROM platforms WHERE slug='hermes'),
  'https://hermes-agent.nousresearch.com', NULL, 'Nous Research', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('系统化根因调试', 'systematic-debugging', '4阶段根因调试法：理解bug→隔离原因→最小修复→验证', '4 阶段调试法：理解 bug→隔离原因→最小修复→验证。防止"改了再说"的盲改。方法论型 Skill，理解即用，无需配置。', 'efficiency', (SELECT id FROM platforms WHERE slug='hermes'),
  'https://hermes-agent.nousresearch.com', NULL, 'Nous Research', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('TDD 强制流程', 'test-driven-development', 'TDD强制流程：先写测试→跑失败→写实现→跑通过→重构', '强制 RED-GREEN-REFACTOR：先写测试→跑失败→写实现→跑通过→重构。概念清晰，但需要项目有测试框架。', 'efficiency', (SELECT id FROM platforms WHERE slug='hermes'),
  'https://hermes-agent.nousresearch.com', NULL, 'Nous Research', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('HyperFrames 视频创作引擎', 'hyperframes', '视频创作引擎：文字/URL/Figma→视频动画，7子Skill+7运行时', '从文字/URL/Figma/代码生成视频动画。7 个子 Skill（core/animation/keyframes/cli/creative/registry）。支持 GSAP、Lottie、Three.js 等 7 种运行时适配器。Hermes 生态中最重的内容创作工具，OpenClaw 没有对应物。', 'scene', (SELECT id FROM platforms WHERE slug='hermes'),
  'https://hermes-agent.nousresearch.com', NULL, 'Nous Research', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('宝玉信息图生成', 'baoyu-infographic', '21种布局×21种风格的信息图/可视化图表生成', '21 种布局 × 21 种风格的信息图/可视化图表生成。描述需求即生成，布局风格参数化。纯 HTML/CSS 输出。', 'scene', (SELECT id FROM platforms WHERE slug='hermes'),
  'https://hermes-agent.nousresearch.com', NULL, 'Nous Research', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('流行 Web 设计系统库', 'popular-web-designs', '54套真实设计系统(Stripe/Linear/Vercel/Apple)直接套用', '54 套真实设计系统（Stripe / Linear / Vercel / Apple 风格），写前端代码时直接套用。选风格即用。', 'efficiency', (SELECT id FROM platforms WHERE slug='hermes'),
  'https://hermes-agent.nousresearch.com', NULL, 'Nous Research', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('YouTube 内容处理', 'youtube-content', 'YouTube字幕提取→摘要/推文/博客/线程', 'YouTube 字幕提取→摘要/推文/博客/线程。一键将视频转为文字内容。传 URL 即可。', 'scene', (SELECT id FROM platforms WHERE slug='hermes'),
  'https://hermes-agent.nousresearch.com', NULL, 'Nous Research', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('Google Workspace 全家桶', 'google-workspace', 'Gmail/Calendar/Drive/Sheets/Docs统一API操作', 'Gmail / Calendar / Drive / Sheets / Docs 统一 API 操作。需 OAuth2 配置（google-workspace-setup skill 辅助）。Google API 稳定，token 刷新偶尔需手动。', 'efficiency', (SELECT id FROM platforms WHERE slug='hermes'),
  'https://hermes-agent.nousresearch.com', NULL, 'Nous Research', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('邮箱分诊', 'email-inbox-triage', '扫描收件箱→按紧急程度分类→安全草拟回复', '扫描收件箱→按紧急程度分类→安全草拟回复。需配 IMAP/SMTP（himalaya CLI）。', 'efficiency', (SELECT id FROM platforms WHERE slug='hermes'),
  'https://hermes-agent.nousresearch.com', NULL, 'Nous Research', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('Obsidian 知识库管理', 'obsidian-skill', '多Obsidian vault搜索/创建笔记，跨笔记链接管理', '多 Obsidian vault 搜索/创建笔记，跨笔记链接管理。安装 obsidian-cli 即用。', 'efficiency', (SELECT id FROM platforms WHERE slug='hermes'),
  'https://hermes-agent.nousresearch.com', NULL, 'Nous Research', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('Apple Notes 管理', 'apple-notes-skill', '通过memo CLI创建/搜索/编辑Apple Notes', '通过 memo CLI 创建/搜索/编辑 Apple Notes。macOS 原生，零配置。', 'efficiency', (SELECT id FROM platforms WHERE slug='hermes'),
  'https://hermes-agent.nousresearch.com', NULL, 'Nous Research', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('iMessage 收发', 'imessage-skill', '通过imsg CLI收发iMessage/SMS，Agent代为回复消息', '通过 imsg CLI 收发 iMessage/SMS。Agent 可代为回复消息。macOS 原生。AppleScript 桥接偶尔有权限弹窗。', 'efficiency', (SELECT id FROM platforms WHERE slug='hermes'),
  'https://hermes-agent.nousresearch.com', NULL, 'Nous Research', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('AI 工具评测框架', 'ai-tool-evaluation', '评测AI工具/Coze技能/GPTs标准5问框架+横向对比', '评测 AI 工具/Coze 技能/GPTs 时的标准 5 问框架（场景/上手/稳定/免费额度/Token 成本）+ 横向对比。方法论型 Skill。这就是本评测平台正在使用的框架本身。', 'efficiency', (SELECT id FROM platforms WHERE slug='hermes'),
  'https://hermes-agent.nousresearch.com', NULL, 'Nous Research', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('Skill Vetter', 'openclaw-skill-vetter', 'OpenClaw安全审查员：安装社区Skill前后自动扫描红旗（必装第一个）', '安装任何社区 Skill 前后自动扫描红旗：权限滥用、密钥泄露、提示注入、可疑命令。ClawHavoc 后持续迭代，规则库覆盖主要攻击模式。OpenClaw 用户第一个必须安装的 Skill。256K 下载（全平台第一）。', 'infrastructure', (SELECT id FROM platforms WHERE slug='openclaw'),
  'https://clawhub.com/skills/skill-vetter', NULL, 'Koi Security', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('Gog', 'openclaw-gog', 'Google全家桶一站式：Gmail+Calendar+Drive+Docs+Sheets+Contacts', 'Gmail + Calendar + Drive + Docs + Sheets + Contacts 一个 Skill 全覆盖。"发 Q3 报告给 Sarah 并加周四下午 2 点的会"——一句话触发两个 Google 服务。@steipete（OpenClaw 创始人）出品。185K 下载。', 'efficiency', (SELECT id FROM platforms WHERE slug='openclaw'),
  'https://clawhub.com/skills/gog', NULL, '@steipete', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('Web Browsing', 'openclaw-web-browsing', '让Agent打开网页、提取内容、追踪链接（基础设施）', '让 Agent 打开网页、提取内容、追踪链接。几乎所有实用工作流的起点。零配置（bundled 或一键安装）。180K+ 下载。', 'infrastructure', (SELECT id FROM platforms WHERE slug='openclaw'),
  'https://clawhub.com/skills/web-browsing', NULL, '@steipete', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('Supermemory / Self-Improving-Agent', 'openclaw-supermemory', '跨会话长期记忆：本地nomic-embed-text向量化+SQLite，LongMemEval 95.4%', '跨会话长期记忆。Supermemory 用本地 nomic-embed-text 向量化，SQLite + 向量索引，数据不上传。Self-Improving-Agent 捕获学习经验。LongMemEval 基准准确率 95.4%。Self-Improving-Agent 42.9K 下载。', 'infrastructure', (SELECT id FROM platforms WHERE slug='openclaw'),
  'https://clawhub.com/skills/supermemory', NULL, '@steipete', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('Github', 'openclaw-github', '通过对话管理Issue/PR/CI，不用切换到GitHub UI', '通过对话管理 Issue、PR、CI。不用切换到 GitHub UI。@steipete 出品。189K 下载。', 'efficiency', (SELECT id FROM platforms WHERE slug='openclaw'),
  'https://clawhub.com/skills/github', NULL, '@steipete', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('Playwright Browser Automation', 'openclaw-playwright', '无头浏览器控制：101个工具覆盖导航/点击/表单/截图/数据提取', '基于 Playwright 的无头浏览器控制。101 个工具覆盖导航/点击/表单/截图/数据提取。支持 stealth 模式绕过反爬。数据抓取场景首选。', 'efficiency', (SELECT id FROM platforms WHERE slug='openclaw'),
  'https://clawhub.com/skills/playwright-browser', NULL, '@executeautomation', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('Felo Search', 'openclaw-felo-search', 'AI搜索附引用：直接返回AI整合答案+每个结论附来源引用', '不是丢链接让 Agent 自己读，而是直接返回 AI 整合答案 + 每个结论附来源引用。搜索到行动从 3-4 轮缩到 1 轮。多语言支持好（中文效果优于多数搜索 Skill）。', 'infrastructure', (SELECT id FROM platforms WHERE slug='openclaw'),
  'https://clawhub.com/skills/felo-search', NULL, 'Felo', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('Summarize Pro', 'openclaw-summarize-pro', '万物摘要：URL/PDF/文档/邮件/YouTube字幕→摘要', 'URL / PDF / 文档 / 邮件 / YouTube 字幕→摘要。"总结这个 45 分钟视频"省 44 分钟。传内容即用。29K 下载。', 'efficiency', (SELECT id FROM platforms WHERE slug='openclaw'),
  'https://clawhub.com/skills/summarize-pro', NULL, '@steipete', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('Ontology', 'openclaw-ontology', '类型化知识图谱：存有关系的数据，Agent能沿关系链推理', '类型化知识图谱。不像 Self-Improving-Agent 存文本，Ontology 存有关系的数据："这个联系人在某客户公司工作"。Agent 能沿关系链推理。188K 下载。', 'infrastructure', (SELECT id FROM platforms WHERE slug='openclaw'),
  'https://clawhub.com/skills/ontology', NULL, '@steipete', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('Notion / Obsidian', 'openclaw-notion', '知识库集成：Notion全API+Obsidian本地Markdown模糊搜索', 'Notion：全 API（页面/数据库/block）。Obsidian：本地 Markdown，隐私优先，模糊搜索 + 维基链接。@steipete 出品。Notion 91.8K 下载；Obsidian 102K 下载。', 'efficiency', (SELECT id FROM platforms WHERE slug='openclaw'),
  'https://clawhub.com/skills/notion', NULL, '@steipete', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('Multi Search Engine', 'openclaw-multi-search', '17个搜索引擎聚合，无需任何API key', '17 个搜索引擎聚合，无需任何 API key。零配置，安装即用。152K 下载。', 'infrastructure', (SELECT id FROM platforms WHERE slug='openclaw'),
  'https://clawhub.com/skills/multi-search', NULL, '@anthropic', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('Felo Slides', 'openclaw-felo-slides', 'AI简报生成：描述需求→生成专业PPTX，每页元素可独立编辑', '描述需求→生成专业 PPTX。每页元素可独立编辑（非扁平图片）。返回下载链接 + LiveDoc 在线编辑地址。异步流程（提交任务→轮询→下载）健壮。', 'scene', (SELECT id FROM platforms WHERE slug='openclaw'),
  'https://clawhub.com/skills/felo-slides', NULL, 'Felo', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('Telegram', 'openclaw-telegram', '移动端接入：手机不在电脑前也能给Agent发消息处理任务', '手机不在电脑前也能给 Agent 发消息处理任务。BotFather 建 bot token，5 分钟接入。145K+ 下载（全平台第二）。', 'efficiency', (SELECT id FROM platforms WHERE slug='openclaw'),
  'https://clawhub.com/skills/telegram', NULL, '@steipete', '2026-08', 'published', FALSE, NULL, 'manual', NOW()),
('Database Query', 'openclaw-database-query', '自然语言查数据库：自然语言→SQL→执行→格式化结果', '接 PostgreSQL/MySQL/SQLite，自然语言→SQL→执行→格式化结果。"上周注册了多少用户"。必须用只读连接，建议限非生产环境。95K+ 下载。', 'efficiency', (SELECT id FROM platforms WHERE slug='openclaw'),
  'https://clawhub.com/skills/database-query', NULL, '@executeautomation', '2026-08', 'published', FALSE, NULL, 'manual', NOW())
ON CONFLICT (slug) DO NOTHING;

-- ---- 2b. 评测记录 ----
INSERT INTO evaluations (skill_id, scenario_summary, difficulty_score, difficulty_notes,
  stability_score, stability_notes, free_quota, free_quota_score, token_cost, token_efficiency_score,
  overall_score, evaluated_by, evaluation_method, version_at_eval, evaluated_at) VALUES
((SELECT id FROM skills WHERE slug='hermes-self-improvement'), '能力增强工具集：KB/成本/决策/错误/纠正/验证/网关/记忆。startup 自动加载，是 Hermes 防幻觉和质量管控中枢',
  4, '8 个子模块功能丰富，需理解每个模块的触发条件和能力边界', 5, '核心基础设施，startup 自动加载，逻辑确定',
  '完全免费（本地）', 5, '低-中（按需加载子模块）', 4,
  4.6, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='hermes-hooks'), 'Hook 驱动引擎：21 种 Hook + 40 条 Plugin 规则，进程级拦截在 LLM 调用前/工具调用前强制执行规则',
  4, '21 种 Hook 类型需要理解，但每种都有文档和示例', 5, '进程级拦截，逻辑确定，核心基础设施',
  '完全免费（本地）', 5, '极低（Hook 本身不消耗 token，拦截反而省 token）', 5,
  4.8, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='hook-first-methodology'), '做方案选择时强制用最强机制：Plugin/Hook > Cron > Memory > Skill',
  4, '概念简单（机制强度排序），但需要理解每种 hook 的能力边界', 5, '逻辑确定性，无外部依赖',
  '免费', 5, '几乎为零（纯方法论指导）', 5,
  4.8, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='hermes-knowledge-base'), 'DuckDB + text2vec 768 维向量搜索，72 篇文档。中文语义检索项目文档、历史决策、技术方案',
  3, '需部署 DuckDB + 配置 text2vec。77 篇以下文档直接读文件更快', 4, 'DuckDB 成熟稳定。向量索引重建偶尔有延迟',
  '完全免费（本地）', 5, '中。kb_vec.py 注入检索结果约 500-2000 token', 3,
  3.8, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='claude-code'), '将编码任务委派给 Claude Code CLI。Print 模式非交互一次性任务，PTY 模式多轮迭代',
  3, '需安装 Claude Code + OAuth 登录。两种模式选择有学习成本', 4, 'Print 模式非常可靠。PTY 交互偶尔有对话框超时',
  'Claude Pro $20/月含额度；API 按 token 计费', 2, '高。Claude Code 自身消耗大量 token（Sonnet $3/$15 per M token）', 2,
  3.0, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='github-pr-workflow'), '分支创建→提交→开 PR→CI 监控→自动修复→合并。双路径设计（gh CLI + curl 降级）',
  5, '文档极其完整。每个步骤有 gh 方式和 curl 降级方式', 5, 'GitHub API 稳定。CI 轮询逻辑健壮（30s 间隔，最多 20 次）',
  '免费（GitHub API 免费层 5000 req/h）', 5, '极低（API 调用，不消耗 LLM token）', 5,
  5.0, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='systematic-debugging'), '4 阶段调试法：理解 bug→隔离原因→最小修复→验证。防止"改了再说"的盲改',
  5, '方法论型 Skill，理解即用，无需配置', 5, '逻辑确定',
  '免费', 5, '低（调试过程引导，本身不额外消耗 token）', 5,
  5.0, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='test-driven-development'), '强制 RED-GREEN-REFACTOR：先写测试→跑失败→写实现→跑通过→重构',
  4, '概念清晰，但需要项目有测试框架', 5, '逻辑确定',
  '免费', 5, '中。写测试代码增加 token 消耗，但减少后续调试成本', 3,
  4.4, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='hyperframes'), '从文字/URL/Figma/代码生成视频动画。7 个子 Skill + 7 种运行时适配器（GSAP/Lottie/Three.js 等）',
  2, '复杂度最高。需理解 HTML composition + data-* timing + seek-safe 渲染。CLI 工作流有学习曲线', 4, '单时间线确定性渲染。云渲染（HeyGen/AWS Lambda/GCP Cloud Run）多路径',
  '本地渲染免费。云渲染按用量（AWS Lambda ~$0.02/次）', 4, '高。多 Skill 联动（7 个子 Skill）+ 复杂 HTML 生成', 2,
  3.2, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='baoyu-infographic'), '21 种布局 × 21 种风格的信息图/可视化图表生成',
  4, '描述需求即生成，布局风格参数化', 4, '纯 HTML/CSS 输出，确定性高',
  '免费（纯 HTML/CSS 输出）', 5, '中。复杂信息图约 2000-5000 token', 3,
  4.0, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='popular-web-designs'), '54 套真实设计系统（Stripe / Linear / Vercel / Apple 风格），写前端代码时直接套用',
  5, '选风格即用', 5, '静态资源，确定性高',
  '免费', 5, '低（设计 token 注入约 300-800 token）', 5,
  5.0, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='youtube-content'), 'YouTube 字幕提取→摘要/推文/博客/线程。一键将视频转为文字内容',
  5, '传 URL 即可', 4, '依赖 YouTube 字幕 API，偶尔有速率限制',
  '免费', 5, '中。字幕全文注入（10-30 分钟视频约 5000-15000 token）', 3,
  4.2, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='google-workspace'), 'Gmail / Calendar / Drive / Sheets / Docs 统一 API 操作',
  3, '需 OAuth2 配置（google-workspace-setup skill 辅助）', 4, 'Google API 稳定，token 刷新偶尔需手动',
  '免费（Google API 免费层充足）', 5, '低（API 调用为主）', 5,
  4.2, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='email-inbox-triage'), '扫描收件箱→按紧急程度分类→安全草拟回复',
  3, '需配 IMAP/SMTP（himalaya CLI）', 4, '稳定',
  '免费', 5, '中。邮件全文 + 分类 + 草拟回复约 2000-8000 token', 3,
  3.8, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='obsidian-skill'), '多 Obsidian vault 搜索/创建笔记，跨笔记链接管理',
  4, '安装 obsidian-cli 即用', 5, '稳定',
  '免费', 5, '低-中（取决于检索量）', 4,
  4.6, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='apple-notes-skill'), '通过 memo CLI 创建/搜索/编辑 Apple Notes',
  5, 'macOS 原生，零配置', 5, '稳定',
  '免费', 5, '低', 5,
  5.0, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='imessage-skill'), '通过 imsg CLI 收发 iMessage/SMS。Agent 可代为回复消息',
  4, 'macOS 原生', 4, 'AppleScript 桥接偶尔有权限弹窗',
  '免费', 5, '低', 5,
  4.4, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='ai-tool-evaluation'), '评测 AI 工具/Coze 技能/GPTs 时的标准 5 问框架 + 横向对比',
  5, '方法论型', 5, '逻辑确定',
  '免费', 5, '零', 5,
  5.0, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='openclaw-skill-vetter'), '安装任何社区 Skill 前后自动扫描红旗：权限滥用、密钥泄露、提示注入、可疑命令',
  5, '安装即生效，自动拦截', 4, 'ClawHavoc 后持续迭代，规则库覆盖主要攻击模式',
  '免费', 5, '低（扫描规则匹配为主）', 5,
  4.6, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='openclaw-gog'), 'Gmail + Calendar + Drive + Docs + Sheets + Contacts 一个 Skill 全覆盖',
  3, '需 OAuth 授权（比 Hermes google-workspace 多一个 Contacts）', 5, '@steipete（OpenClaw 创始人 Peter Steinberger）出品，质量等同第一方',
  '免费（Google API）', 5, '低', 5,
  4.6, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='openclaw-web-browsing'), '让 Agent 打开网页、提取内容、追踪链接。几乎所有实用工作流的起点',
  5, '零配置（bundled 或一键安装）', 4, '成熟。但只能访问页面，不能搜索（搜索需搭配 Felo Search / Tavily）',
  '免费', 5, '中。网页内容提取后注入上下文（1000-10000 token）', 3,
  4.2, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='openclaw-supermemory'), '跨会话长期记忆。Supermemory 用本地 nomic-embed-text 向量化，SQLite + 向量索引。LongMemEval 基准准确率 95.4%',
  3, 'Supermemory 需配置嵌入模型；Self-Improving-Agent 开箱即用', 4, 'Supermemory 本地运行稳定。AgentCore 插件（AWS 版）提供四策略提取',
  'Supermemory 免费本地部署。阿里云百炼记忆插件有免费额度', 4, '中。记忆检索注入 500-2000 token/次', 3,
  3.6, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='openclaw-github'), '通过对话管理 Issue、PR、CI。不用切换到 GitHub UI',
  3, '需 OAuth 授权', 5, '@steipete 出品',
  '免费', 5, '低（API 调用）', 5,
  4.6, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='openclaw-playwright'), '基于 Playwright 的无头浏览器控制。101 个工具覆盖导航/点击/表单/截图/数据提取。支持 stealth 模式绕过反爬',
  3, '需理解 CSS 选择器。browser_launch → browser_goto → browser_evaluate 流程', 4, 'Playwright 成熟。stealth 模式对 Cloudflare 有效但非 100%',
  '免费（本地 Playwright）', 5, '高。复杂爬取场景 Agent 需编写/调试脚本，多轮交互', 2,
  3.6, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='openclaw-felo-search'), '不是丢链接让 Agent 自己读，而是直接返回 AI 整合答案 + 每个结论附来源引用。搜索到行动从 3-4 轮缩到 1 轮',
  4, '需 FELO_API_KEY（felo.ai 免费获取）。多语言支持好', 4, 'Felo API 稳定',
  '有免费层', 4, '中。AI 整合答案注入约 500-2000 token', 3,
  3.8, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='openclaw-summarize-pro'), 'URL / PDF / 文档 / 邮件 / YouTube 字幕→摘要。"总结这个 45 分钟视频"省 44 分钟',
  5, '传内容即用', 4, '稳定',
  '免费', 5, '中-高。长内容全文处理（10000-50000 token）', 2,
  4.0, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='openclaw-ontology'), '类型化知识图谱。存有关系的数据："这个联系人在某客户公司工作"。Agent 能沿关系链推理',
  3, '需理解图数据库概念', 4, '稳定',
  '免费', 5, '中。图谱查询 + 推理注入', 3,
  3.8, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='openclaw-notion'), 'Notion：全 API（页面/数据库/block）。Obsidian：本地 Markdown，隐私优先，模糊搜索 + 维基链接',
  3, 'Notion 需 OAuth；Obsidian 需安装 obsidian-cli', 5, '@steipete 出品',
  '免费', 5, '低', 5,
  4.6, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='openclaw-multi-search'), '17 个搜索引擎聚合，无需任何 API key',
  5, '零配置，安装即用', 4, '依赖各搜索引擎页面结构，偶尔有解析失败',
  '完全免费', 5, '中。多引擎结果聚合后 token 量大', 3,
  4.2, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='openclaw-felo-slides'), '描述需求→生成专业 PPTX。每页元素可独立编辑。返回下载链接 + LiveDoc 在线编辑地址',
  4, '需 FELO_API_KEY。自动处理异步轮询', 4, '异步流程（提交任务→轮询→下载）健壮',
  '有免费层', 4, '中（描述 + 轮询结果）', 3,
  3.8, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='openclaw-telegram'), '手机不在电脑前也能给 Agent 发消息处理任务。BotFather 建 bot token，5 分钟接入',
  4, '简单', 4, '延迟比预期低',
  '免费（Telegram Bot API 免费）', 5, '低-中（取决于任务复杂度）', 4,
  4.2, 'AI-First 5问框架', 'ai_first', '2026-08', NOW()),
((SELECT id FROM skills WHERE slug='openclaw-database-query'), '接 PostgreSQL/MySQL/SQLite，自然语言→SQL→执行→格式化结果。"上周注册了多少用户"',
  3, '需配置连接字符串。必须用只读连接，建议限非生产环境', 4, 'SQL 生成准确度高。凭证管理需小心',
  '免费', 5, '中（Schema + 查询 + 结果）', 3,
  3.8, 'AI-First 5问框架', 'ai_first', '2026-08', NOW())
;

-- ============================================================
-- 3. 基础收录 Skill（88 个）— 仅 INSERT INTO skills，无评测
-- ============================================================

INSERT INTO skills (name, slug, tagline, category, platform_id, install_url, icon_url,
                    developer_name, version, status, trial_enabled, trial_config, source, last_updated) VALUES
('A股/港股/美股实时数据', 'coze-stock-realtime', 'A股/港股/美股实时行情与市场动态数据查询', 'scene', (SELECT id FROM platforms WHERE slug='coze'),
  'https://www.coze.cn/skill-store', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('量化股票分析', 'coze-quant-stock', '依托A股数据库的专业量化选股多维度分析工具', 'scene', (SELECT id FROM platforms WHERE slug='coze'),
  'https://www.coze.cn/skill-store', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('投资机构观点', 'coze-inst-viewpoints', '总结投资机构研报观点，含盈利预测和评级', 'scene', (SELECT id FROM platforms WHERE slug='coze'),
  'https://www.coze.cn/skill-store', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('龙虎榜', 'coze-dragon-tiger', 'A股龙虎榜数据查询，游资席位追踪', 'scene', (SELECT id FROM platforms WHERE slug='coze'),
  'https://www.coze.cn/skill-store', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('ETF筛选', 'coze-etf-filter', 'ETF基金筛选与资金异动监控', 'scene', (SELECT id FROM platforms WHERE slug='coze'),
  'https://www.coze.cn/skill-store', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('iSlide PPT生成', 'coze-islide-ppt', '一键生成高质量PPT，自动匹配模板', 'efficiency', (SELECT id FROM platforms WHERE slug='coze'),
  'https://www.coze.cn/skill-store', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Seedance 视频创作', 'coze-seedance', '剧本→分镜→剪辑→配音→成片全流程AI自动生成', 'scene', (SELECT id FROM platforms WHERE slug='coze'),
  'https://www.coze.cn/skill-store', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('World Bank Open Data', 'coze-worldbank', '世界银行经济数据多维度查询与分析', 'scene', (SELECT id FROM platforms WHERE slug='coze'),
  'https://www.coze.cn/skill-store', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('OpenEcon 开源经济数据', 'coze-openecon', '多维度经济数据信息快速查询', 'scene', (SELECT id FROM platforms WHERE slug='coze'),
  'https://www.coze.cn/skill-store', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('法律咨询技能包', 'coze-legal-pack', '扣子官方法律行业技能组合包', 'scene', (SELECT id FROM platforms WHERE slug='coze'),
  'https://www.coze.cn/skill-store', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('金融严选技能包', 'coze-finance-pack', '金融行业一站式技能组合(ETF/龙虎榜/定投等)', 'scene', (SELECT id FROM platforms WHERE slug='coze'),
  'https://www.coze.cn/skill-store', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('自媒体内容创作技能', 'coze-selfmedia', '自动搜热点、写标题、写文案、写脚本', 'scene', (SELECT id FROM platforms WHERE slug='coze'),
  'https://www.coze.cn/skill-store', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('办公自动化技能', 'coze-office-auto', '周报月报、会议纪要、数据分析、PPT大纲生成', 'efficiency', (SELECT id FROM platforms WHERE slug='coze'),
  'https://www.coze.cn/skill-store', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('编程开发技能', 'coze-coding', '扣子官方编程技能，支持CLI深度开发', 'infrastructure', (SELECT id FROM platforms WHERE slug='coze'),
  'https://www.coze.cn/skill-store', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('教育备课技能', 'coze-edu-prep', '教学备课、课件生成、知识点总结', 'scene', (SELECT id FROM platforms WHERE slug='coze'),
  'https://www.coze.cn/skill-store', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('电商运营技能包', 'coze-ecommerce-pack', '电商行业技能组合(商品/客服/营销)', 'scene', (SELECT id FROM platforms WHERE slug='coze'),
  'https://www.coze.cn/skill-store', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Video Maker by invideo AI', 'gpt-invideo-ai', '将文本/文档/PDF秒转AI视频，适配YouTube/TikTok/Reels', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Write for Me', 'gpt-write-for-me', '精准字数控制的高质量内容写作GPT', 'efficiency', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Canva GPT', 'gpt-canva', '自然语言生成社交媒体图片、海报、营销素材', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Zapier GPT', 'gpt-zapier', '连接5000+应用实现工作流自动化', 'efficiency', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('ScholarAI', 'gpt-scholarai', 'AI学术研究助手，论文检索与引用', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Consensus', 'gpt-consensus', '基于2亿篇论文的科学研究问答引擎', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Code Copilot', 'gpt-code-copilot', '多语言编程助手，支持Python/JS/Go等', 'infrastructure', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Grimoire', 'gpt-grimoire', '革命性编程GPT，从想法到代码全流程', 'infrastructure', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Screenshot to Code', 'gpt-screenshot-to-code', '截图秒转前端代码(HTML/React)', 'infrastructure', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Diagrams: Show Me', 'gpt-diagrams', '自然语言生成可编辑的流程图/架构图', 'efficiency', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Data Analyst', 'gpt-data-analyst', '拖入文件即可分析和可视化数据', 'efficiency', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Copywriter GPT', 'gpt-copywriter', '病毒式营销策略与品牌文案生成', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('AI Humanizer', 'gpt-ai-humanizer', '将AI生成文本改写为自然人类语气', 'efficiency', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Hemingway Editor GPT', 'gpt-hemingway', '简化复杂句子，提升文本可读性', 'efficiency', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Tutor Me (Khan Academy)', 'gpt-tutor-me', 'Khan Academy个性化辅导AI', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Math Solver', 'gpt-math-solver', '高级数学问题求解与步骤讲解', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Prompt Perfect', 'gpt-prompt-perfect', '自动优化提示词以获得更好AI输出', 'efficiency', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Logo Creator', 'gpt-logo-creator', 'AI Logo设计生成器', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Presentation Creator by SlideSpeak', 'gpt-slidespeak', 'ChatGPT内直接生成精美PPT演示文稿', 'efficiency', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('DesignerGPT', 'gpt-designergpt', '自然语言生成网页设计与布局', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('ChatPRD', 'gpt-chatprd', '产品经理AI助手，PRD文档撰写', 'efficiency', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('CrewAI Assistant', 'gpt-crewai', 'CrewAI多智能体框架编程助手', 'infrastructure', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Travel Guide GPT', 'gpt-travel-guide', '个性化旅行规划与目的地推荐', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Fitness Workout Diet Coach', 'gpt-fitness-coach', '定制化健身计划与营养方案', 'scene', (SELECT id FROM platforms WHERE slug='gpts'),
  'https://chatgpt.com/gpts', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Anthropic DOCX Skill', 'claude-docx', 'Word文档创建/编辑，含目录、页码、信头、修订', 'infrastructure', (SELECT id FROM platforms WHERE slug='claude'),
  'https://github.com/anthropics/skills', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Anthropic PDF Skill', 'claude-pdf', 'PDF读取/创建/合并/拆分/水印/加密/填表/OCR', 'infrastructure', (SELECT id FROM platforms WHERE slug='claude'),
  'https://github.com/anthropics/skills', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Anthropic PPTX Skill', 'claude-pptx', 'PowerPoint演示文稿生成/编辑，含幻灯片和演讲备注', 'infrastructure', (SELECT id FROM platforms WHERE slug='claude'),
  'https://github.com/anthropics/skills', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Anthropic XLSX Skill', 'claude-xlsx', 'Excel电子表格创建/编辑，公式/格式/图表', 'infrastructure', (SELECT id FROM platforms WHERE slug='claude'),
  'https://github.com/anthropics/skills', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Skill Creator', 'claude-skill-creator', '交互式技能创建工具，含评估测试', 'infrastructure', (SELECT id FROM platforms WHERE slug='claude'),
  'https://github.com/anthropics/skills', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('MCP Builder', 'claude-mcp-builder', '构建MCP Server的官方技能', 'infrastructure', (SELECT id FROM platforms WHERE slug='claude'),
  'https://github.com/anthropics/skills', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Claude API Skill', 'claude-api', 'Claude API/SDK开发辅助技能', 'infrastructure', (SELECT id FROM platforms WHERE slug='claude'),
  'https://github.com/anthropics/skills', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Webapp Testing', 'claude-webapp-testing', 'Playwright浏览器自动化测试技能', 'infrastructure', (SELECT id FROM platforms WHERE slug='claude'),
  'https://github.com/anthropics/skills', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Doc Co-authoring', 'claude-doc-coauthoring', '协作式长文写作，分段起草含人工反馈', 'efficiency', (SELECT id FROM platforms WHERE slug='claude'),
  'https://github.com/anthropics/skills', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Brand Guidelines', 'claude-brand-guidelines', '应用Anthropic官方品牌色彩与排版', 'scene', (SELECT id FROM platforms WHERE slug='claude'),
  'https://github.com/anthropics/skills', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Algorithmic Art', 'claude-algo-art', 'p5.js生成艺术：流场/粒子系统/噪声层叠', 'scene', (SELECT id FROM platforms WHERE slug='claude'),
  'https://github.com/anthropics/skills', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Internal Comms', 'claude-internal-comms', '撰写内部通讯如状态报告/简报/FAQ', 'efficiency', (SELECT id FROM platforms WHERE slug='claude'),
  'https://github.com/anthropics/skills', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Claude Code /code-review', 'claude-code-review', '官方代码审查技能，分析diff并给inline评论', 'infrastructure', (SELECT id FROM platforms WHERE slug='claude-code'),
  'https://github.com/anthropics/skills', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Claude Code /batch', 'claude-code-batch', '大任务拆分为单元并在隔离worktree并行执行', 'infrastructure', (SELECT id FROM platforms WHERE slug='claude-code'),
  'https://github.com/anthropics/skills', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Claude Code /verify', 'claude-code-verify', '构建并运行应用观察结果，超越仅测试', 'infrastructure', (SELECT id FROM platforms WHERE slug='claude-code'),
  'https://github.com/anthropics/skills', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Write Tests Skill', 'claude-write-tests', '自动编写测试，社区高人气自定义技能', 'infrastructure', (SELECT id FROM platforms WHERE slug='claude-code'),
  'https://github.com/anthropics/skills', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Frontend Design Skill', 'claude-frontend-design', '官方前端设计技能，生成非AI感的Web界面', 'scene', (SELECT id FROM platforms WHERE slug='claude'),
  'https://github.com/anthropics/skills', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Filesystem MCP', 'mcp-filesystem', '带权限控制的本地文件读写操作', 'infrastructure', (SELECT id FROM platforms WHERE slug='mcp'),
  'https://github.com/modelcontextprotocol/servers', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('GitHub MCP', 'mcp-github', 'GitHub仓库/Issue/PR/工作流/安全管理', 'infrastructure', (SELECT id FROM platforms WHERE slug='mcp'),
  'https://github.com/modelcontextprotocol/servers', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Playwright MCP', 'mcp-playwright', '官方浏览器自动化，页面检查/截图/交互', 'infrastructure', (SELECT id FROM platforms WHERE slug='mcp'),
  'https://github.com/modelcontextprotocol/servers', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Sequential Thinking MCP', 'mcp-sequential-thinking', '动态反思式结构化推理，适合架构决策和调试', 'infrastructure', (SELECT id FROM platforms WHERE slug='mcp'),
  'https://github.com/modelcontextprotocol/servers', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Memory MCP', 'mcp-memory', '基于知识图谱的跨会话持久记忆', 'infrastructure', (SELECT id FROM platforms WHERE slug='mcp'),
  'https://github.com/modelcontextprotocol/servers', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Context7 MCP', 'mcp-context7', '为AI提供最新版本文档，避免过时示例', 'infrastructure', (SELECT id FROM platforms WHERE slug='mcp'),
  'https://context7.com', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Fetch MCP', 'mcp-fetch', 'Web内容抓取并转换为LLM友好格式', 'infrastructure', (SELECT id FROM platforms WHERE slug='mcp'),
  'https://github.com/modelcontextprotocol/servers', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Git MCP', 'mcp-git', '读取/搜索/操作Git仓库', 'infrastructure', (SELECT id FROM platforms WHERE slug='mcp'),
  'https://github.com/modelcontextprotocol/servers', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Time MCP', 'mcp-time', '时间和时区转换能力', 'infrastructure', (SELECT id FROM platforms WHERE slug='mcp'),
  'https://github.com/modelcontextprotocol/servers', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Postgres MCP', 'mcp-postgres', 'PostgreSQL数据库查询与管理', 'infrastructure', (SELECT id FROM platforms WHERE slug='mcp'),
  'https://github.com/modelcontextprotocol/servers', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Notion MCP', 'mcp-notion', '访问Notion页面/数据库/任务', 'efficiency', (SELECT id FROM platforms WHERE slug='mcp'),
  'https://github.com/modelcontextprotocol/servers', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Supabase MCP', 'mcp-supabase', '连接Supabase边缘函数与Postgres', 'infrastructure', (SELECT id FROM platforms WHERE slug='mcp'),
  'https://github.com/modelcontextprotocol/servers', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Slack MCP', 'mcp-slack', 'Slack消息读取与发送', 'efficiency', (SELECT id FROM platforms WHERE slug='mcp'),
  'https://github.com/modelcontextprotocol/servers', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Linear MCP', 'mcp-linear', 'Linear项目管理Issue/项目集成', 'efficiency', (SELECT id FROM platforms WHERE slug='mcp'),
  'https://github.com/modelcontextprotocol/servers', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Brave Search MCP', 'mcp-brave-search', 'Brave搜索引擎Web搜索', 'infrastructure', (SELECT id FROM platforms WHERE slug='mcp'),
  'https://github.com/modelcontextprotocol/servers', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Puppeteer MCP', 'mcp-puppeteer', '无头Chrome浏览器自动化', 'infrastructure', (SELECT id FROM platforms WHERE slug='mcp'),
  'https://github.com/modelcontextprotocol/servers', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Sentry MCP', 'mcp-sentry', 'Sentry错误追踪与日志集成', 'infrastructure', (SELECT id FROM platforms WHERE slug='mcp'),
  'https://github.com/modelcontextprotocol/servers', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Terraform MCP', 'mcp-terraform', 'HashiCorp IaC基础设施即代码自然语言管理', 'infrastructure', (SELECT id FROM platforms WHERE slug='mcp'),
  'https://github.com/hashicorp/terraform-mcp', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Datadog MCP', 'mcp-datadog', '统一访问日志/指标/追踪/APM数据', 'infrastructure', (SELECT id FROM platforms WHERE slug='mcp'),
  'https://github.com/datadog/mcp-server', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Kubernetes MCP', 'mcp-kubernetes', 'Kubernetes集群管理与查询', 'infrastructure', (SELECT id FROM platforms WHERE slug='mcp'),
  'https://github.com/mark3d/mcp-kubernetes', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Proxmox MCP', 'mcp-proxmox', 'Proxmox虚拟化管理平台集成', 'infrastructure', (SELECT id FROM platforms WHERE slug='mcp'),
  'https://github.com/nickclyde/proxmox-mcp', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Chrome DevTools MCP', 'mcp-chrome-devtools', '调试网页，检查DOM/CSS', 'infrastructure', (SELECT id FROM platforms WHERE slug='mcp'),
  'https://github.com/modelcontextprotocol/servers', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Dify Workflow Builder', 'dify-workflow', '可视化AI工作流拖拽构建器', 'infrastructure', (SELECT id FROM platforms WHERE slug='dify'),
  'https://dify.ai', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Dify RAG Engine', 'dify-rag', '检索增强生成引擎，知识库问答', 'infrastructure', (SELECT id FROM platforms WHERE slug='dify'),
  'https://dify.ai', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Dify Agent', 'dify-agent', '可推理、使用工具、保持上下文的自主Agent', 'infrastructure', (SELECT id FROM platforms WHERE slug='dify'),
  'https://dify.ai', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Dify Knowledge Pipeline', 'dify-knowledge', '文件/网站/文档的提取/清洗/分块/索引流水线', 'infrastructure', (SELECT id FROM platforms WHERE slug='dify'),
  'https://dify.ai', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Dify difyctl', 'dify-ctl', 'Dify命令行工具，面向终端/脚本/编程Agent', 'infrastructure', (SELECT id FROM platforms WHERE slug='dify'),
  'https://github.com/langgenius/dify', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Agensi Skill Marketplace', 'agensi-marketplace', '跨Claude/ChatGPT/Cursor的2000+技能市场', 'infrastructure', (SELECT id FROM platforms WHERE slug='agensi'),
  'https://agenssi.io/skills', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Poe Bot Creator', 'poe-bot-creator', 'Poe平台创建跨模型Bot(Claude/GPT/Gemini)', 'infrastructure', (SELECT id FROM platforms WHERE slug='poe'),
  'https://poe.com', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('Flowise', 'flowise', '可视化LangChain AI应用构建器', 'infrastructure', (SELECT id FROM platforms WHERE slug='flowise'),
  'https://github.com/FlowiseAI/Flowise', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW()),
('n8n Workflow', 'n8n', '开源工作流自动化，支持AI节点', 'efficiency', (SELECT id FROM platforms WHERE slug='n8n'),
  'https://n8n.io', NULL, NULL, NULL, 'published', FALSE, NULL, 'listed', NOW())
ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- 4. Skill × 场景关联
-- ============================================================
INSERT INTO skill_scenarios (skill_id, scenario_id) VALUES
  ((SELECT id FROM skills WHERE slug='hermes-self-improvement'), (SELECT id FROM scenarios WHERE slug='memory')),
  ((SELECT id FROM skills WHERE slug='hermes-hooks'), (SELECT id FROM scenarios WHERE slug='security')),
  ((SELECT id FROM skills WHERE slug='hook-first-methodology'), (SELECT id FROM scenarios WHERE slug='automation')),
  ((SELECT id FROM skills WHERE slug='hermes-knowledge-base'), (SELECT id FROM scenarios WHERE slug='memory')),
  ((SELECT id FROM skills WHERE slug='hermes-knowledge-base'), (SELECT id FROM scenarios WHERE slug='research')),
  ((SELECT id FROM skills WHERE slug='claude-code'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='github-pr-workflow'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='systematic-debugging'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='test-driven-development'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='hyperframes'), (SELECT id FROM scenarios WHERE slug='video')),
  ((SELECT id FROM skills WHERE slug='hyperframes'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='baoyu-infographic'), (SELECT id FROM scenarios WHERE slug='design')),
  ((SELECT id FROM skills WHERE slug='baoyu-infographic'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='popular-web-designs'), (SELECT id FROM scenarios WHERE slug='ui-design')),
  ((SELECT id FROM skills WHERE slug='popular-web-designs'), (SELECT id FROM scenarios WHERE slug='design')),
  ((SELECT id FROM skills WHERE slug='youtube-content'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='google-workspace'), (SELECT id FROM scenarios WHERE slug='office')),
  ((SELECT id FROM skills WHERE slug='email-inbox-triage'), (SELECT id FROM scenarios WHERE slug='office')),
  ((SELECT id FROM skills WHERE slug='obsidian-skill'), (SELECT id FROM scenarios WHERE slug='office')),
  ((SELECT id FROM skills WHERE slug='apple-notes-skill'), (SELECT id FROM scenarios WHERE slug='office')),
  ((SELECT id FROM skills WHERE slug='imessage-skill'), (SELECT id FROM scenarios WHERE slug='office')),
  ((SELECT id FROM skills WHERE slug='ai-tool-evaluation'), (SELECT id FROM scenarios WHERE slug='research')),
  ((SELECT id FROM skills WHERE slug='openclaw-skill-vetter'), (SELECT id FROM scenarios WHERE slug='security')),
  ((SELECT id FROM skills WHERE slug='openclaw-gog'), (SELECT id FROM scenarios WHERE slug='office')),
  ((SELECT id FROM skills WHERE slug='openclaw-web-browsing'), (SELECT id FROM scenarios WHERE slug='search')),
  ((SELECT id FROM skills WHERE slug='openclaw-supermemory'), (SELECT id FROM scenarios WHERE slug='memory')),
  ((SELECT id FROM skills WHERE slug='openclaw-github'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='openclaw-playwright'), (SELECT id FROM scenarios WHERE slug='automation')),
  ((SELECT id FROM skills WHERE slug='openclaw-felo-search'), (SELECT id FROM scenarios WHERE slug='search')),
  ((SELECT id FROM skills WHERE slug='openclaw-summarize-pro'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='openclaw-ontology'), (SELECT id FROM scenarios WHERE slug='memory')),
  ((SELECT id FROM skills WHERE slug='openclaw-ontology'), (SELECT id FROM scenarios WHERE slug='research')),
  ((SELECT id FROM skills WHERE slug='openclaw-notion'), (SELECT id FROM scenarios WHERE slug='office')),
  ((SELECT id FROM skills WHERE slug='openclaw-multi-search'), (SELECT id FROM scenarios WHERE slug='search')),
  ((SELECT id FROM skills WHERE slug='openclaw-felo-slides'), (SELECT id FROM scenarios WHERE slug='design')),
  ((SELECT id FROM skills WHERE slug='openclaw-felo-slides'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='openclaw-telegram'), (SELECT id FROM scenarios WHERE slug='office')),
  ((SELECT id FROM skills WHERE slug='openclaw-database-query'), (SELECT id FROM scenarios WHERE slug='data-analysis')),
  ((SELECT id FROM skills WHERE slug='coze-stock-realtime'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='coze-quant-stock'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='coze-inst-viewpoints'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='coze-dragon-tiger'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='coze-etf-filter'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='coze-islide-ppt'), (SELECT id FROM scenarios WHERE slug='automation')),
  ((SELECT id FROM skills WHERE slug='coze-seedance'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='coze-worldbank'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='coze-openecon'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='coze-legal-pack'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='coze-finance-pack'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='coze-selfmedia'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='coze-office-auto'), (SELECT id FROM scenarios WHERE slug='automation')),
  ((SELECT id FROM skills WHERE slug='coze-coding'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='coze-edu-prep'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='coze-ecommerce-pack'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='gpt-invideo-ai'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='gpt-write-for-me'), (SELECT id FROM scenarios WHERE slug='automation')),
  ((SELECT id FROM skills WHERE slug='gpt-canva'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='gpt-zapier'), (SELECT id FROM scenarios WHERE slug='automation')),
  ((SELECT id FROM skills WHERE slug='gpt-scholarai'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='gpt-consensus'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='gpt-code-copilot'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='gpt-grimoire'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='gpt-screenshot-to-code'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='gpt-diagrams'), (SELECT id FROM scenarios WHERE slug='automation')),
  ((SELECT id FROM skills WHERE slug='gpt-data-analyst'), (SELECT id FROM scenarios WHERE slug='automation')),
  ((SELECT id FROM skills WHERE slug='gpt-copywriter'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='gpt-ai-humanizer'), (SELECT id FROM scenarios WHERE slug='automation')),
  ((SELECT id FROM skills WHERE slug='gpt-hemingway'), (SELECT id FROM scenarios WHERE slug='automation')),
  ((SELECT id FROM skills WHERE slug='gpt-tutor-me'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='gpt-math-solver'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='gpt-prompt-perfect'), (SELECT id FROM scenarios WHERE slug='automation')),
  ((SELECT id FROM skills WHERE slug='gpt-logo-creator'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='gpt-slidespeak'), (SELECT id FROM scenarios WHERE slug='automation')),
  ((SELECT id FROM skills WHERE slug='gpt-designergpt'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='gpt-chatprd'), (SELECT id FROM scenarios WHERE slug='automation')),
  ((SELECT id FROM skills WHERE slug='gpt-crewai'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='gpt-travel-guide'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='gpt-fitness-coach'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='claude-docx'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='claude-pdf'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='claude-pptx'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='claude-xlsx'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='claude-skill-creator'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='claude-mcp-builder'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='claude-api'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='claude-webapp-testing'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='claude-doc-coauthoring'), (SELECT id FROM scenarios WHERE slug='automation')),
  ((SELECT id FROM skills WHERE slug='claude-brand-guidelines'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='claude-algo-art'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='claude-internal-comms'), (SELECT id FROM scenarios WHERE slug='automation')),
  ((SELECT id FROM skills WHERE slug='claude-code-review'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='claude-code-batch'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='claude-code-verify'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='claude-write-tests'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='claude-frontend-design'), (SELECT id FROM scenarios WHERE slug='content-creation')),
  ((SELECT id FROM skills WHERE slug='mcp-filesystem'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='mcp-github'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='mcp-playwright'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='mcp-sequential-thinking'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='mcp-memory'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='mcp-context7'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='mcp-fetch'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='mcp-git'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='mcp-time'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='mcp-postgres'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='mcp-notion'), (SELECT id FROM scenarios WHERE slug='automation')),
  ((SELECT id FROM skills WHERE slug='mcp-supabase'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='mcp-slack'), (SELECT id FROM scenarios WHERE slug='automation')),
  ((SELECT id FROM skills WHERE slug='mcp-linear'), (SELECT id FROM scenarios WHERE slug='automation')),
  ((SELECT id FROM skills WHERE slug='mcp-brave-search'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='mcp-puppeteer'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='mcp-sentry'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='mcp-terraform'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='mcp-datadog'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='mcp-kubernetes'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='mcp-proxmox'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='mcp-chrome-devtools'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='dify-workflow'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='dify-rag'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='dify-agent'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='dify-knowledge'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='dify-ctl'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='agensi-marketplace'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='poe-bot-creator'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='flowise'), (SELECT id FROM scenarios WHERE slug='code')),
  ((SELECT id FROM skills WHERE slug='n8n'), (SELECT id FROM scenarios WHERE slug='automation'))
ON CONFLICT DO NOTHING;

-- ============================================================
-- 5. 同类替代关系
-- ============================================================
INSERT INTO skill_alternatives (skill_id, alternative_skill_id, note) VALUES
  ((SELECT id FROM skills WHERE slug='hermes-knowledge-base'), (SELECT id FROM skills WHERE slug='openclaw-ontology'), NULL),
  ((SELECT id FROM skills WHERE slug='claude-code'), (SELECT id FROM skills WHERE slug='openclaw-github'), NULL),
  ((SELECT id FROM skills WHERE slug='github-pr-workflow'), (SELECT id FROM skills WHERE slug='openclaw-github'), NULL),
  ((SELECT id FROM skills WHERE slug='baoyu-infographic'), (SELECT id FROM skills WHERE slug='openclaw-felo-slides'), NULL),
  ((SELECT id FROM skills WHERE slug='youtube-content'), (SELECT id FROM skills WHERE slug='openclaw-summarize-pro'), NULL),
  ((SELECT id FROM skills WHERE slug='google-workspace'), (SELECT id FROM skills WHERE slug='openclaw-gog'), NULL),
  ((SELECT id FROM skills WHERE slug='obsidian-skill'), (SELECT id FROM skills WHERE slug='openclaw-notion'), NULL),
  ((SELECT id FROM skills WHERE slug='imessage-skill'), (SELECT id FROM skills WHERE slug='openclaw-telegram'), NULL),
  ((SELECT id FROM skills WHERE slug='openclaw-gog'), (SELECT id FROM skills WHERE slug='google-workspace'), NULL),
  ((SELECT id FROM skills WHERE slug='openclaw-supermemory'), (SELECT id FROM skills WHERE slug='openclaw-ontology'), NULL),
  ((SELECT id FROM skills WHERE slug='openclaw-github'), (SELECT id FROM skills WHERE slug='github-pr-workflow'), NULL),
  ((SELECT id FROM skills WHERE slug='openclaw-summarize-pro'), (SELECT id FROM skills WHERE slug='youtube-content'), NULL),
  ((SELECT id FROM skills WHERE slug='openclaw-ontology'), (SELECT id FROM skills WHERE slug='hermes-knowledge-base'), NULL),
  ((SELECT id FROM skills WHERE slug='openclaw-notion'), (SELECT id FROM skills WHERE slug='obsidian-skill'), NULL),
  ((SELECT id FROM skills WHERE slug='openclaw-felo-slides'), (SELECT id FROM skills WHERE slug='baoyu-infographic'), NULL),
  ((SELECT id FROM skills WHERE slug='openclaw-telegram'), (SELECT id FROM skills WHERE slug='imessage-skill'), NULL),
  ((SELECT id FROM skills WHERE slug='openclaw-gog'), (SELECT id FROM skills WHERE slug='google-workspace'), 'OpenClaw 6合1集成度更高'),
  ((SELECT id FROM skills WHERE slug='openclaw-github'), (SELECT id FROM skills WHERE slug='github-pr-workflow'), 'Hermes版双路径降级更健壮'),
  ((SELECT id FROM skills WHERE slug='openclaw-summarize-pro'), (SELECT id FROM skills WHERE slug='youtube-content'), 'OpenClaw版更通用(多格式)'),
  ((SELECT id FROM skills WHERE slug='openclaw-telegram'), (SELECT id FROM skills WHERE slug='imessage-skill'), 'Telegram跨平台 vs iMessage Apple限定'),
  ((SELECT id FROM skills WHERE slug='openclaw-ontology'), (SELECT id FROM skills WHERE slug='hermes-knowledge-base'), '知识图谱关系推理 vs 向量搜索'),
  ((SELECT id FROM skills WHERE slug='openclaw-felo-slides'), (SELECT id FROM skills WHERE slug='baoyu-infographic'), 'PPT生成 vs 信息图')
ON CONFLICT DO NOTHING;

-- ============================================================
-- 6. 幂等收敛：更新各平台 skill_count
-- ============================================================
UPDATE platforms p SET skill_count = v.cnt FROM (VALUES
  ('hermes',25),
  ('openclaw',14),
  ('coze',29),
  ('gpts',25),
  ('claude',15),
  ('claude-code',4),
  ('mcp',22),
  ('dify',6),
  ('agensi',1),
  ('poe',1),
  ('flowise',1),
  ('n8n',1),
  ('codex',1),
  ('ernie',1),
  ('qwen',1)
) AS v(slug, cnt) WHERE p.slug = v.slug;

-- ============================================================
-- 总计: 150 个 Skill
--   init.sql 已有: 30
--   本文件新增评测: 32
--   本文件新增收录: 88
--   新增平台: 7
-- ============================================================